ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.thiakil.SerializationKt.configureSerialization
      - com.thiakil.ShutdownUrlKt.configureShutdownUrl
      - com.thiakil.RoutingKt.configureRouting
      - com.thiakil.WebsocketsKt.configureWebsockets
      - com.thiakil.TunerApiKt.tunerApi
