ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.thaikil.SerializationKt.configureSerialization
      - com.thaikil.ShutdownUrlKt.configureShutdownUrl
      - com.thaikil.RoutingKt.configureRouting
