const ENGLISH_GENERAL = [
  /*0*/ "No programme type",
  /*1*/ "News",
  /*2*/ "Current Affairs",
  /*3*/ "Information",
  /*4*/ "Sport",
  /*5*/ "Education",
  /*6*/ "Drama",
  /*7*/ "Culture",
  /*8*/ "Science",
  /*9*/ "Varied",
  /*10*/ "Pop Music",
  /*11*/ "Rock Music",
  /*12*/ "Easy Listening Music",
  /*13*/ "Light Classical",
  /*14*/ "Serious Classical",
  /*15*/ "Other Music",
  /*16*/ "Weather/meteorology",
  /*17*/ "Finance/Business",
  /*18*/ "Children's programmes",
  /*19*/ "Social Affairs",
  /*20*/ "Religion",
  /*21*/ "Phone In",
  /*22*/ "Travel",
  /*23*/ "Leisure",
  /*24*/ "Jazz Music",
  /*25*/ "Country Music",
  /*26*/ "National Music",
  /*27*/ "Oldies Music",
  /*28*/ "Folk Music",
  /*29*/ "Documentary",
  /*30*/ "Unused",
  /*31*/ "Unused",
];

const ENGLISH_NORTH_AMERICA = [
  /*0*/ "No program type",
  /*1*/ "News",
  /*2*/ "Information",
  /*3*/ "Sports",
  /*4*/ "Talk",
  /*5*/ "Rock",
  /*6*/ "Classic Rock",
  /*7*/ "Adult Hits",
  /*8*/ "Soft Rock",
  /*9*/ "Top 40",
  /*10*/ "Country",
  /*11*/ "Oldies",
  /*12*/ "Soft",
  /*13*/ "Nostalgia",
  /*14*/ "Jazz",
  /*15*/ "Classical",
  /*16*/ "Rhythm and Blues",
  /*17*/ "Soft Rhythm and Blues",
  /*18*/ "Foreign Language",
  /*19*/ "Religious Music",
  /*20*/ "Religious Talk",
  /*21*/ "Personality",
  /*22*/ "Public",
  /*23*/ "College",
  /*24*/ "RESERVED",
  /*25*/ "RESERVED",
  /*26*/ "RESERVED",
  /*27*/ "RESERVED",
  /*28*/ "RESERVED",
  /*29*/ "Weather",
  /*30*/ "Unused",
  /*31*/ "Unused",
]


const DUTCH = [
  "niet gedefinieerd",
  "Nieuws",
  "Actualiteit",
  "Informatie",
  "Sport",
  "Educatie",
  "Drama",
  "Cultuur",
  "Wetenschap",
  "Varia en gesprekken",
  "Pop",
  "Rock",
  "Melodie: ontspanningsmuziek",
  "Licht klassiek",
  "Klassiek",
  "Overige muziek",
  "Weerbericht",
  "Economie",
  "Voor kinderen",
  "Maatschappelijk",
  "Religie",
  "Doe mee !",
  "Reizen",
  "Vrije tijd",
  "Jazz",
  "Country",
  "Nationale muziek",
  "Gouwe Ouwe",
  "Volksmuziek",
  "Documentaires",
]

const FRENCH = [
  "Codification de programme non utilisée ou genre non défini",
  "Informations",
  "Magazine",
  "Info-Service",
  "Sport",
  "Education",
  "Dramatique",
  "Culture",
  "Sciences",
  "Divertissement",
  "Pop",
  "Rock",
  "Chansons",
  "Classique Léger",
  "Musique Classique",
  "Autre Musique",
  "Météo",
  "Economie et Finances",
  "Programmes pour enfants",
  "Société",
  "Religion",
  "Ligne ouverte et interactivité",
  "Voyages",
  "Loisirs",
  "Musique de jazz",
  "Musique de country",
  "Chansons du pays",
  "Musique rétro",
  "Musique folklorique",
  "Documentaire",
]

const GERMAN = [
  "Keine Programmartkennung",
  "Nachrichtendienst",
  "Politik und Zeitgeschehen",
  "Service Programm",
  "Sport",
  "Lernen und Weiterbildung",
  "Hörspiel und Literatur",
  "Kultur, Kirche und Gesellschaft",
  "Wissenschaft",
  "Unterhaltendes Wort",
  "Popmusik",
  "Rockmusik",
  "Unterhaltungsmusik",
  "Leichte klassische Musik",
  "Ernste klassische Musik",
  "Spezielle Musikprogramme",
  "Wetter",
  "Wirtschaft",
  "Kinderprogramm",
  "Soziales",
  "Religion",
  "Anrufsendung",
  "Reiseinformation",
  "Freizeit",
  "Jazz",
  "Countrymusik",
  "Musik des Landes",
  "Oldiemusik",
  "Folklore",
  "Feature",
]

const NORWEGIAN = [
  "Ingen programtype eller udefinert",
  "Nyheter",
  "Aktuell reportasje",
  "Informasjon",
  "Sport",
  "Undervisning",
  "Radioteater",
  "Kultur",
  "Vitenskap",
  "Underholdning",
  "Pop musikk",
  "Rock musikk",
  "Lett musikk",
  "Underholdningsmusikk",
  "Klassisk musikk",
  "Diverse musikk",
  "Værmelding",
  "Økonomi",
  "Barneprogram",
  "Sosialprogram",
  "Religion",
  "Innringing",
  "Reiseprogram",
  "Fritidsprogram",
  "Jazz",
  "Countrymusikk",
  "Nasjonal musikk",
  "Gammelpop",
  "Folkemusikk",
  "Dokumentar",
]

const PORTUGUESE = [
  "Não definido",
  "Notícias",
  "Actualidade",
  "Informação",
  "Desporto",
  "Educação",
  "Teatro Radiofónico",
  "Cultura",
  "Ciência",
  "Variado",
  "Música Pop",
  "Música Rock",
  "Música Ligeira",
  "Clássica Ligeira",
  "Música Clássica",
  "Outras Músicas",
  "Meteorologia",
  "Economia",
  "Programa Infantil",
  "Acontec Sociais",
  "Religião",
  "Telefonemas dos ouvintes",
  "Viagens",
  "Lazer",
  "Música de Jazz",
  "Música Country",
  "Música Nacional",
  "Música Antiga",
  "Música Folk",
  "Documentário",
]

const SPANISH = [
  "No se indica el tipo programa",
  "Noticias",
  "Magazin",
  "Información",
  "Deportes",
  "Educación",
  "Drama",
  "Cultura",
  "Ciencia",
  "Varios",
  "Música Pop",
  "Música Rock",
  "Grand éxitos",
  "Música Ligera",
  "Música Clásica",
  "Otra Música",
  "Información Metereológica",
  "Economia",
  "Infancia",
  "Sociedad",
  "Religión",
  "Opinión",
  "Viajes",
  "Ocio",
  "Música Jazz",
  "Música Country",
  "Música Nacional",
  "Música de ayer",
  "Música Folk",
  "Documental",
]

const SWEDISH = [
  "Programtypen saknas eller är odefinierad",
  "Korta nyheter",
  "Fördjupning av nyheter",
  "Allmän information",
  "Sport",
  "Utbildningsprogram",
  "Teater och program om teater",
  "Kultur i bred mening",
  "Vetenskapsprogram",
  "Underhållningsprogram",
  "Populärmusik",
  "Rockmusik",
  "Underhållningsmusik",
  "Lätt klassisk musik(ej kompletta verk)",
  "Kompletta klassiska verk",
  "Övrig Musik",
  "Väderraporter",
  "Ekonomiprogram",
  "Barnprogram",
  "Program om sociala frågor",
  "Andliga frågor",
  "Telefonväkteri",
  "Resor och semester",
  "Fritid och hobby",
  "Jazzmusik",
  "Countrymusik",
  "Nationell musik",
  "Klassisk pop",
  "Folkmusik",
  "Dokumentärer",
]

const FINNISH = [
  "Ei ohjelmatyyppiä",
  "Uutiset",
  "Ajankohtaista",
  "Tiedotuksia",
  "Urheilu",
  "Opetus",
  "Kuunnelma",
  "Kulttuuri",
  "Tiede",
  "Puheviihde",
  "Pop-musiikki",
  "Rock-musiikki",
  "Kevyt musiikki",
  "Kevyt klassinen musiikki",
  "Klassinen musiikki",
  "Muu musiikki",
  "Säätiedotus",
  "Talousohjelma",
  "Lastenohjelma",
  "Yhteiskunta",
  "Uskonto",
  "Yleisökontakti",
  "Matkailu",
  "Vapaa-aika",
  "Jazz-musiikki",
  "Country-musiikki",
  "Kotimainen musiikki",
  "Aikuisten musiikki",
  "Kansanmusiikki",
  "Dokumentti",
]

const DANISH = [
  "Ej defineret",
  "Nyheder",
  "Aktuelt",
  "Almen information",
  "Sport",
  "Undervisning",
  "Drama",
  "Kultur",
  "Videnskab",
  "Varieret underholdning",
  "Pop musik",
  "Rock musik",
  "Underholdnings musik",
  "Let Klassisk musik",
  "Klassisk musik",
  "Blandet musik",
  "Vejrudsigt",
  "Økonimi & Erhverv",
  "Børne programmer",
  "Program om sociale emner",
  "Kirke & Tro",
  "Telefon program",
  "Rejser & Ferie",
  "Hobby & Fritid",
  "Jazz musik",
  "Country musik",
  "Dansktop musik",
  "Gamle kendinge",
  "Folke musik",
  "Dokumentar program",
]

const ITALIAN = [
  "Non trasmesso/non definito",
  "Ultime Notizie",
  "Attualità, Magazine",
  "Informazioni",
  "Notizie Sportive",
  "Programmi Educativi",
  "Commedia e Teatro",
  "Programmi Culturali",
  "Programmi Scientifici",
  "Vari Generi",
  "Musica Pop",
  "Musica Rock",
  "Musica Leggera",
  "Musica Classica Leggera",
  "Musica Classica",
  "Altri Generi di Musica",
  "Previsioni del Tempo",
  "Economia e Finanza",
  "Programmi per Ragazzi",
  "Programmi Sociali",
  "Programmi Religiosi",
  "Forum, Opinioni",
  "Viaggi",
  "Svago",
  "Musica Jazz",
  "Musica Country",
  "Musica Italiana",
  "Vecchi Successi",
  "Musica Popolare",
  "Documentari",
]

const LITHUANIAN = [
  "Programos tipas neapibrėžtas",
  "Žinios",
  "Aktualijos",
  "Informacija",
  "Sportas",
  "Šviečiamosios",
  "Radijo teatras",
  "Kultūra",
  "Mokslas",
  "Įvairūs",
  "Pop muzika",
  "Roko muzika",
  "Lengvoji muzika",
  "Populiarioji klasikinė muzika",
  "Klasikinė muzika",
  "Kitų žanrų muzika",
  "Oras",
  "Finansai",
  "Laidos vaikams",
  "Visuomeninės laidos",
  "Religinės laidos",
  "Skambučiai į studiją",
  "Kelionės",
  "Laisvalaikis",
  "Džiazas",
  "Kantri",
  "Liaudies muzika",
  "Seni hitai",
  "Folkloras",
  "Dokumentika",
]

const POLISH = [
  "Brak typu programu lub niezdefiniowany",
  "Wiadomości",
  "Wydarzenia Bieżące",
  "Informacje",
  "Sport",
  "Edukacja",
  "Dramat",
  "Kultura",
  "Nauka",
  "Różne",
  "Muzyka Pop",
  "Muzyka Rock",
  "Muzyka Łatwa",
  "Muzyka Klasyczna Lekka",
  "Muzyka Klasyczna Poważna",
  "Muzyka Inna",
  "Pogoda",
  "Finanse",
  "Programy Dziecięce",
  "Wydarzenia Społeczne",
  "Religia",
  "Audycja Z Telefonicznym Udziałem Słuchaczy",
  "Podruże",
  "Czas Wolny",
  "Muzyka Jazzowa",
  "Muzyka Country",
  "Muzyka Narodowa",
  "Muzyka Archiwalna",
  "Muzyka Ludowa",
  "Dokument",
]

const ROMANIAN = [
  "Tip de program nedefinit",
  "Radiojurnal",
  "Actualităţi, magazin",
  "Informaţii",
  "Sport",
  "Program educativ",
  "Teatru",
  "Program cultural",
  "Program ştiinţific",
  "Varietăţi",
  "Muzică pop",
  "Muzică rock",
  "Muzică Uşoară",
  "Muzică clasică accesibilă",
  "Muzică clasică",
  "Altă muzică",
  "Prognoza Meteo",
  "Finanţe şi economie",
  "Programe pentru copii",
  "Actualităţi sociale",
  "Religie",
  "Dialog cu ascultătorii",
  "Călătorii",
  "Timp liber",
  "Muzică de jazz",
  "Muzică country",
  "Muzică Românească",
  "Muzica retro",
  "Muzică Populară",
  "Documentar",
]

const SLOVENIAN = [
  "Neopredeljeno",
  "Novice",
  "Aktualna dogajanja",
  "Obvestila",
  "Šport",
  "Izobraževanje",
  "Dramatizirana zvočna predstava",
  "Kultura",
  "Znanost",
  "Razno",
  "Pop glasba",
  "Rock glasba",
  "Razvedrilna glasba",
  "Lahka klasična glasba",
  "Resna klasična glasba",
  "Druga glasba",
  "Vreme",
  "Finance",
  "Otroški program",
  "Družba",
  "Religija",
  "Pogovorna oddaja",
  "Potovanja",
  "Prosti čas",
  "Jazz glasba",
  "Country glasba",
  "Domača glasba",
  "Stari hiti",
  "Narodna glasba",
  "Dokumentarna oddaja",
]

const BULGARIAN = [
  "Без Име",
  "Новини",
  "Актуално Предаване",
  "Информация",
  "Спорт",
  "Образование",
  "Радио Театър",
  "Култура",
  "Наука",
  "Разни Развлечение",
  "Поп Музика",
  "Рок Музика",
  "Музика За Релакс",
  "Лека Класика",
  "Класика",
  "Музика",
  "Прогноза За Времето",
  "Икономика",
  "Предаване За Деца",
  "Общество",
  "Религия",
  "Слушателско Включване Открита Линия",
  "Туризъм",
  "Хоби Свободно Време",
  "Джаз",
  "Кънтри Музика",
  "Българска Музикa",
  "Ретро Музика",
  "Народна Музика",
  "Документалистика",
]

const CROATIAN = [
  "Neodređeno",
  "Vijesti",
  "Aktualna događanja",
  "Obavijesti",
  "Sport",
  "Obrazovanje",
  "Drama",
  "Kultura",
  "Znanost",
  "Razno",
  "Pop glazba",
  "Rock glazba",
  "Zabavna glazba",
  "Lagana klasična glazba",
  "Ozbiljna glazba",
  "Ostala glazba",
  "Vrijeme",
  "Financije",
  "Dječji program",
  "Društvena događanja",
  "Religija",
  "Kontakt program",
  "Putovanja",
  "Slobodno vrijeme",
  "Jazz glazba",
  "Country glazba",
  "Domaća glazba",
  "Stari hitovi",
  "Narodna glazba",
  "Dokumentarno",
]

const CZECH = [
  "Nedefinovaný program",
  "Zprávy",
  "Publicistika",
  "Informace",
  "Sport",
  "Vzdělání",
  "Drama",
  "Kultura",
  "Věda",
  "Různé",
  "Pop Music",
  "Rock Music",
  "Oddychová hudba",
  "Klasika",
  "Vážná hudba",
  "Jiná hudba",
  "Počasí",
  "Finance",
  "Dětský program",
  "Společenská tematika",
  "Naboženská tematika",
  "Telefonáty",
  "Cestování",
  "Zábava",
  "Jazzová hudba",
  "Country hudba",
  "Národní hudba",
  "Oldies hudba",
  "Folková hudba",
  "Dokumentární program",
]

const ESTONIAN = [
  "Programmi tüüp puudub",
  "Uudised",
  "Päevakajalised teemad",
  "Informatsioon d",
  "Spordisaade",
  "Haridussaade",
  "Kuuldemäng",
  "Kultuurisaade",
  "Teadussaade",
  "Mitmesugused teemad",
  "Pop muusika",
  "Rock muusika",
  "Meeleolumuusika",
  "Kerge klassikaline muusika",
  "Klassikaline muusika",
  "Muu muusika",
  "Ilmateade",
  "Majandussaade",
  "Lastesaade",
  "Sotsiaalsaated",
  "Ususaade",
  "Telefonikontakt",
  "Reisisaade",
  "Vaba aeg ja hobid",
  "Jazzmuusika",
  "Kantrimuusika",
  "Rahvamuusika",
  "Retromuusika",
  "Folkmuusika",
  "Dokumentaalsaade",
]

const HUNGARIAN = [
  "Nincs program típus",
  "Hírek",
  "Magazin",
  "Információ",
  "Sport",
  "Oktatás",
  "Hangjáték",
  "Kultúra",
  "Tudományos műsor",
  "Vegyes",
  "Popzene",
  "Rockzene",
  "Könnyűzene",
  "Klasszikus zene",
  "Komolyzene",
  "Egyéb zene",
  "Időjárás",
  "Pénzügyi, gazdasági műsor",
  "Gyermekműsor",
  "Társadalmi ügyek",
  "Vallási műsor",
  "Telefonos műsor",
  "Utazási információk",
  "Szabadidő",
  "Jazz",
  "Countryzene",
  "Nemzeti zene",
  "Oldies zene",
  "Népzene ne",
  "Dokumentumműsor",
]

const RUSSIAN = [
  "Неопределенный",
  "Новости",
  "Аналитическая",
  "Информационная",
  "Спортивная",
  "Образовательная",
  "Драма",
  "Культура",
  "Наука",
  "Разговорная",
  "Поп",
  "Рок",
  "Лёгкая музыка",
  "Лёгкая классическая музыка",
  "Классическая музыка",
  "Прочая музыка",
  "Погода",
  "Финансы",
  "Детские программы",
  "Социальные темы",
  "Религия",
  "Интерактивные программы",
  "Путешествие",
  "Досуг",
  "Джаз",
  "Кантри музыка",
  "Отечественная музыка",
  "Ретро",
  "Народная музыка",
  "Документальный",
]




export const PROGRAMME_TYPE_TABLES = {
  ENGLISH_GENERAL,
  ENGLISH_NORTH_AMERICA,
  DUTCH,
  FRENCH,
  GERMAN,
  NORWEGIAN,
  PORTUGUESE,
  SPANISH,
  SWEDISH,
  FINNISH,
  DANISH,
  ITALIAN,
  LITHUANIAN,
  POLISH,
  ROMANIAN,
  SLOVENIAN,
  BULGARIAN,
  CROATIAN,
  CZECH,
  ESTONIAN,
  HUNGARIAN,
  RUSSIAN,
}

export const PROGRAMME_TYPE_UNSET = 0xFF;